const assert=require('node:assert/strict');const {chromium}=require('playwright');const fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const p=await b.newPage({viewport:{width:1024,height:768},hasTouch:true,userAgent:'Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{window.nativeCalls=0;Element.prototype.requestFullscreen=async()=>{window.nativeCalls++;};});
 await p.goto(process.env.CREATIVE_TEST_URL||'http://localhost:4190/creative');assert.equal(await p.locator('#talk-friend').count(),0);
 await p.locator('#fullscreen').tap();assert.equal(await p.locator('body').evaluate(e=>e.classList.contains('game-only')),true);assert.equal(await p.evaluate(()=>nativeCalls),0);
 assert.equal(await p.locator('#fullscreen').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.title').isVisible(),false);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const state=await p.evaluate(()=>({viewport:document.querySelector('meta[name="viewport"]').content,userSelect:getComputedStyle(document.body).userSelect,callout:getComputedStyle(document.body).webkitTouchCallout,events:['dblclick','contextmenu','selectstart','gesturestart'].map(name=>!document.dispatchEvent(new Event(name,{cancelable:true}))),pinch:(()=>{const e=new Event('touchmove',{cancelable:true});Object.defineProperty(e,'touches',{value:[{},{}]});return !document.dispatchEvent(e);})()}));
 assert.match(state.viewport,/user-scalable=no/);assert.equal(state.userSelect,'none');assert.ok(state.events.every(Boolean));assert.equal(state.pinch,true);
 const scene=await p.locator('#scene').boundingBox();await p.mouse.click(scene.x+900*scene.width/1000,scene.y+195*scene.height/360);assert.equal(await p.locator('#friend-dialog').isVisible(),true);await p.locator('#close-friend').tap();
 assert.equal(await p.locator('.workshop').isVisible(),false);assert.equal(await p.locator('.collection-bar').isVisible(),false);
 const from=await p.locator('[data-block="sun"]').boundingBox(),to={x:scene.x+(195+5.5*610/8)*scene.width/1000-1,y:scene.y+239*scene.height/360-1,width:2,height:2};await p.mouse.move(from.x+from.width/2,from.y+from.height/2);await p.mouse.down();await p.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:10});await p.mouse.up();assert.equal(await p.evaluate(()=>creativeGame.snapshot().placements[5]),'sun');assert.equal(await p.evaluate(()=>creativeGame.snapshot().guideSlot),7);
 fs.mkdirSync('test-artifacts',{recursive:true});await p.screenshot({path:'test-artifacts/creative-ipad-fullscreen.png'});
 await p.setViewportSize({width:768,height:1024});assert.equal(await p.locator('.workshop').isVisible(),false);const fit=await p.locator('.adventure:not([hidden])').boundingBox();assert.ok(fit.height>950);assert.equal(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight),true);await p.screenshot({path:'test-artifacts/creative-ipad-fullscreen-portrait.png'});
 await p.locator('#fullscreen').tap();assert.equal(await p.locator('body').evaluate(e=>e.classList.contains('game-only')),false);assert.equal(await p.locator('.workshop').isVisible(),true);
 await p.locator('#fullscreen').tap();await p.keyboard.press('Escape');assert.equal(await p.locator('body').evaluate(e=>e.classList.contains('game-only')),false);assert.equal(await p.locator('#pause-dialog').isVisible(),false);
 assert.deepEqual(errors,[]);console.log('PASS: iPad Safari fullscreen fallback, no native API, gesture guards, canvas friend, fullscreen drag, guide progression, exit button/Escape.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
