const assert=require('node:assert/strict');const {chromium}=require('playwright');const fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const p=await b.newPage({viewport:{width:1024,height:900},hasTouch:true,reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{if(!localStorage.getItem('block-creative-bridge-v1:guest'))localStorage.setItem('block-creative-bridge-v1:guest',JSON.stringify({index:0,completed:[0,1,2,3,4,5],gems:80,points:800}));});
 const url=process.env.CREATIVE_TEST_URL||'http://localhost:4190/creative';await p.goto(url);
 assert.equal(await p.evaluate(()=>creativeGame.snapshot().mode),'warden');assert.equal(await p.locator('#warden-game').isVisible(),true);assert.equal(await p.locator('#warden-avatar').getAttribute('aria-label'),'워든');assert.equal(await p.locator('[aria-label$="울타리 안"]').count(),9);
 await p.locator('#check-sentences').click();assert.match(await p.locator('#warden-feedback').innerText(),/먼저/);
 async function drop(n,i){const from=await p.locator(`[data-number="${n}"]`).boundingBox(),to=await p.locator(`[data-answer="${i}"]`).boundingBox();await p.mouse.move(from.x+from.width/2,from.y+from.height/2);await p.mouse.down();await p.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:8});await p.mouse.up();}
 assert.equal(await p.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=100;MonsterArt.portrait(c,'warden');return c.toDataURL()===document.getElementById('warden-avatar').toDataURL();}),true);
 for(const kind of ['pig','skeleton','witch']){assert.ok(await p.locator(`.pixel-dog[data-kind="${kind}"]`).count()>0);assert.equal(await p.evaluate(kind=>{const c=document.createElement('canvas');c.width=c.height=100;MonsterArt.portrait(c,kind);return c.toDataURL()===document.querySelector(`.pixel-dog[data-kind="${kind}"] canvas`).toDataURL();},kind),true);}assert.equal(await p.locator('.pixel-dog[data-kind="rabbit"],.pixel-dog[data-kind="chicken"]').count(),0);assert.match(await p.locator('#sentences').innerText(),/스켈레톤은/);assert.match(await p.locator('#sentences').innerText(),/보랏빛 마녀는/);
 const answers=[[2,3,4,9],[2,2,2,8],[4,2,4,10],[2,3,5,1,2],[1,3,6,5,3]],totals=[9,8,10,10,10],outside=[4,4,5,5,5];
 for(let i=0;i<5;i++){
  await p.locator('#animal-gate').click();assert.equal(await p.locator('.pixel-dog').count(),totals[i]);assert.equal(await p.locator('[aria-label$="울타리 밖"]').count(),outside[i]);
  await p.locator('[data-number="9"]').click();await p.locator('[data-answer="0"]').click();assert.equal(await p.locator('[data-answer="0"]').innerText(),'?');
  if(i===0){await drop(0,0);await drop(0,1);await drop(0,2);await p.locator('#check-sentences').click();assert.equal(await p.locator('#warden-reward').isVisible(),false);assert.equal(await p.evaluate(()=>creativeGame.snapshot().gems),80);}
  for(let j=0;j<answers[i].length;j++)await drop(answers[i][j],j);
  if(i>=3){await drop(answers[i][2],3);await p.locator('#check-sentences').click();assert.equal(await p.locator('#warden-reward').isVisible(),false);assert.match(await p.locator('#warden-speech').innerText(),/짝지으면/);await drop(answers[i][3],3);}
  await p.reload();assert.equal(await p.locator('[data-answer="0"]').innerText(),String(answers[i][0]));
  assert.equal(await p.locator('.round-fence ellipse').count(),3);
  await p.locator('#check-sentences').click();await p.locator('#warden-reward').waitFor();assert.equal(await p.evaluate(()=>creativeGame.snapshot().gems),80+(i+1)*15);
  if(i===0){fs.mkdirSync('test-artifacts',{recursive:true});await p.screenshot({path:'test-artifacts/warden-reward.png',fullPage:true});await p.reload();assert.equal(await p.locator('#warden-reward').isVisible(),true);assert.equal(await p.evaluate(()=>creativeGame.snapshot().gems),95);}
  await p.locator('#warden-next').click();
 }
 assert.equal(await p.locator('#creative-ending').isVisible(),true);assert.match(await p.locator('#creative-ending').innerText(),/더 재미있는 문제가 준비되면/);assert.equal(await p.evaluate(()=>creativeGame.snapshot().mode),'ending');await p.reload();assert.equal(await p.locator('#creative-ending').isVisible(),true);assert.equal(await p.evaluate(()=>creativeGame.snapshot().gems),155);
 await p.locator('#ending-album').click();assert.equal(await p.locator('.badge-card.earned').count(),11);await p.locator('#close-album').click();assert.equal(await p.evaluate(()=>creativeGame.snapshot().mode),'ending');await p.screenshot({path:'test-artifacts/creative-ending.png',fullPage:true});
 await p.evaluate(()=>localStorage.setItem('block-creative-bridge-v1:guest',JSON.stringify({completed:[0,1,2,3,4,5],gems:125,points:1250,warden:{contentVersion:2,index:2,completed:[0,1,2],answers:[4,2,4,10],counted:[0],gateOpen:true}})));await p.reload();assert.equal(await p.evaluate(()=>creativeGame.snapshot().warden.index),3);assert.equal(await p.evaluate(()=>creativeGame.snapshot().gems),125);assert.equal(await p.locator('[data-answer]').count(),5);assert.equal(await p.locator('[data-answer="0"]').innerText(),'?');
 // Last bridge reward is retained during migration, then proceeds to Warden.
 await p.evaluate(()=>localStorage.setItem('block-creative-bridge-v1:guest',JSON.stringify({index:5,completed:[0,1,2,3,4,5],gems:80,points:800,pendingReward:{index:5,fresh:true,gems:30,points:300}})));await p.reload();assert.equal(await p.locator('#reward').isVisible(),true);await p.locator('#reward-next').click();assert.equal(await p.evaluate(()=>creativeGame.snapshot().mode),'warden');
 await p.locator('#warden-fullscreen').click();assert.equal(await p.locator('.workshop').isVisible(),false);await p.locator('#animal-gate').click();await p.locator('#warden-companion').click();assert.match(await p.locator('#warden-speech').innerText(),/같은 종류/);
 const geometry=await p.evaluate(()=>{const f=document.getElementById('animal-field').getBoundingClientRect();return [...document.querySelectorAll('.pixel-dog')].map(d=>{const r=d.getBoundingClientRect();return {inside:d.dataset.region==='inside',corners:[[r.left,r.top],[r.right,r.top],[r.left,r.bottom],[r.right,r.bottom]].map(([x,y])=>{x=(x-f.left)*800/f.width;y=(y-f.top)*400/f.height;return ((x-300)/240)**2+((y-200)/168)**2;})};});});for(const d of geometry)assert.ok(d.corners.every(n=>d.inside?n<1:n>1));
 await p.screenshot({path:'test-artifacts/warden-fullscreen.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);console.log('PASS: bridge-to-Warden migration, diagram counts, drag-only sentences, wrong/missing answers, 5 rewards, restoration/dedup, one-time ending, 11 badges, fullscreen.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
