const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{
const b=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const p=await b.newPage({viewport:{width:1280,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.addInitScript(()=>{if(!localStorage.getItem('seonyul-sunshine-progress-v1'))localStorage.setItem('seonyul-sunshine-progress-v1',JSON.stringify({counts:{zombie:2}}));});
await p.goto('http://localhost:4173/platformer/');const snap=()=>p.evaluate(()=>sunshine.snapshot());assert.equal(await p.locator('#rescued').textContent(),'2');await p.locator('#start').click();
const encounter=async()=>{await p.keyboard.down('ArrowRight');await p.locator('#quiz').waitFor();await p.keyboard.up('ArrowRight');};
await encounter();const original=[await p.locator('#a').textContent(),await p.locator('#b').textContent()];await p.locator('#retreat').click();await encounter();const replacement=[await p.locator('#a').textContent(),await p.locator('#b').textContent()];assert.notDeepEqual(replacement,original,'New encounter gets a new problem');
await p.keyboard.type('99');await p.locator('#submit').click();assert.equal((await snap()).progress.total,2);assert.deepEqual([await p.locator('#a').textContent(),await p.locator('#b').textContent()],replacement,'Wrong attempt keeps current problem');
async function solve(){const sum=Number(await p.locator('#a').textContent())+Number(await p.locator('#b').textContent());await p.keyboard.type(String(sum));await p.locator('#submit').evaluate(e=>{e.click();e.click();});}
await solve();assert.equal((await snap()).progress.total,3);assert.equal((await snap()).progress.badgeCount,2);assert.ok((await p.locator('#badge-reward').textContent()).includes('단짝 친구'));await p.screenshot({path:path.join(__dirname,'../test-artifacts/platformer-badge-reward.png')});await p.locator('#continue').click();
// Walk to the goal but jump onto the last platform to pass above the slime.
const deadline=Date.now()+35000;
while((await snap()).mode!=='clear'){
 assert.ok(Date.now()<deadline,'Goal traversal timeout');const s=await snap();
 if(s.mode==='quiz'){await p.keyboard.up('ArrowRight');await p.keyboard.up('Space');assert.notEqual(await p.locator('#monster-portrait').getAttribute('data-kind'),'slime','Slime must remain uncaught');await solve();await p.locator('#continue').click();}
 else{await p.keyboard.down('ArrowRight');const x=s.player.x;if((x>935&&x<1200)||(x>2005&&x<2270)||(x>2315&&x<2650))await p.keyboard.down('Space');else await p.keyboard.up('Space');await p.waitForTimeout(45);}
}
await p.keyboard.up('ArrowRight');await p.keyboard.up('Space');assert.ok((await snap()).defeated<3);assert.equal((await snap()).monsters.find(m=>m.kind==='slime').defeated,false);const total=(await snap()).progress.total;await p.screenshot({path:path.join(__dirname,'../test-artifacts/platformer-optional-monsters.png')});await p.locator('#next').click();assert.equal((await snap()).stageNumber,2);assert.equal((await snap()).progress.total,total);
await p.locator('#fullscreen-game').click();await p.locator('#open-badges').click();const frozen=(await snap()).player.x;await p.waitForTimeout(150);assert.equal((await snap()).player.x,frozen);assert.equal(await p.locator('.species-badges[data-kind="zombie"] .earned').count(),2);assert.equal(await p.locator('.species-badges[data-kind="slime"] .earned').count(),0);await p.screenshot({path:path.join(__dirname,'../test-artifacts/platformer-badge-album.png')});await p.locator('#close-badges').click();assert.equal((await snap()).mode,'play');await p.locator('#fullscreen-game').click();
await p.reload();assert.equal((await snap()).progress.total,total);await p.locator('#restart').click();assert.equal((await snap()).progress.total,total);assert.equal((await snap()).stageNumber,1);
await p.setViewportSize({width:390,height:844});await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const hud=await p.locator('#open-badges').boundingBox();assert.ok(hud.x>=0&&hud.x+hud.width<=390);await p.locator('#open-badges').click();await p.screenshot({path:path.join(__dirname,'../test-artifacts/platformer-mobile-badges.png')});assert.deepEqual(errors,[]);await b.close();console.log('PASS: fresh encounter problem, stable retry, persistent counts, exact-once badge reward, optional monsters at goal, next stage, fullscreen album/pause, reload/restart and mobile HUD.');
})().catch(e=>{console.error(e);process.exit(1);});
