// Badge Catalog for Craft Runner and Complete! Block Island
export const BADGE_CATALOG = [
  // ─── 크래프트 Runner 배지 ───
  {
    id: 'first-light',
    game: 'runner',
    category: 'math',
    icon: '🔥',
    title: '첫 햇살 마법',
    desc: '수학 대결에서 처음으로 승리하기',
    rarity: 'common',
    rarityName: '새싹',
    rarityColor: '#85a765',
  },
  {
    id: 'math-10',
    game: 'runner',
    category: 'math',
    icon: '🧮',
    title: '열 번의 자신감',
    desc: '수학 대결에서 10번 승리하기',
    rarity: 'rare',
    rarityName: '희귀',
    rarityColor: '#38bdf8',
  },
  {
    id: 'math-30',
    game: 'runner',
    category: 'math',
    icon: '🎓',
    title: '수학 박사',
    desc: '수학 대결에서 30번 승리하기',
    rarity: 'epic',
    rarityName: '영웅',
    rarityColor: '#c084fc',
  },
  {
    id: 'math-100',
    game: 'runner',
    category: 'math',
    icon: '👑',
    title: '수학 황제',
    desc: '수학 대결에서 100번 승리하기',
    rarity: 'legendary',
    rarityName: '전설',
    rarityColor: '#facc15',
  },
  {
    id: 'speed-1',
    game: 'runner',
    category: 'speed',
    icon: '⚡',
    title: '번개 마법사',
    desc: '5초 안에 초고속 정답으로 승리하기',
    rarity: 'rare',
    rarityName: '희귀',
    rarityColor: '#38bdf8',
  },
  {
    id: 'streak-3',
    game: 'runner',
    category: 'combo',
    icon: '🔥',
    title: '3연승 불꽃',
    desc: '실수 없이 3번 연속으로 승리하기',
    rarity: 'rare',
    rarityName: '희귀',
    rarityColor: '#38bdf8',
  },
  {
    id: 'streak-10',
    game: 'runner',
    category: 'combo',
    icon: '🐉',
    title: '불꽃 드래곤',
    desc: '무려 10번 연속으로 정답 행진하기',
    rarity: 'legendary',
    rarityName: '전설',
    rarityColor: '#facc15',
  },
  {
    id: 'wind-unlock',
    game: 'runner',
    category: 'adventure',
    icon: '🌪️',
    title: '바람 모험의 문',
    desc: '몬스터 50마리를 잡고 바람 점프 해금',
    rarity: 'epic',
    rarityName: '영웅',
    rarityColor: '#c084fc',
  },
  {
    id: 'gems-30',
    game: 'runner',
    category: 'treasure',
    icon: '💠',
    title: '반짝 주머니',
    desc: '보물에서 보석 30개 모으기',
    rarity: 'rare',
    rarityName: '희귀',
    rarityColor: '#38bdf8',
  },
  {
    id: 'gems-100',
    game: 'runner',
    category: 'treasure',
    icon: '💰',
    title: '보석 왕국',
    desc: '보물에서 보석 100개 모으기',
    rarity: 'epic',
    rarityName: '영웅',
    rarityColor: '#c084fc',
  },
  {
    id: 'zombie-1',
    game: 'runner',
    category: 'monster',
    icon: '🧟',
    title: '좀비 햇살 친구',
    desc: '좀비 몬스터를 햇살 마법으로 정화하기',
    rarity: 'common',
    rarityName: '새싹',
    rarityColor: '#85a765',
  },
  {
    id: 'creeper-1',
    game: 'runner',
    category: 'monster',
    icon: '🌿',
    title: '크리퍼 진정 대장',
    desc: '초록 크리퍼를 부드럽게 진정시키기',
    rarity: 'common',
    rarityName: '새싹',
    rarityColor: '#85a765',
  },
  {
    id: 'skeleton-1',
    game: 'runner',
    category: 'monster',
    icon: '🦴',
    title: '달그락 뼈 박사',
    desc: '스켈레톤 몬스터에게 덧셈 승리하기',
    rarity: 'common',
    rarityName: '새싹',
    rarityColor: '#85a765',
  },
  {
    id: 'enderdragon-1',
    game: 'runner',
    category: 'monster',
    icon: '🐉',
    title: '엔더드래곤 정복자',
    desc: '전설의 엔더드래곤 대결에서 승리하기',
    rarity: 'legendary',
    rarityName: '전설',
    rarityColor: '#facc15',
  },

  // ─── 완성! block island 배지 ───
  {
    id: 'island-fox-bridge',
    game: 'island',
    category: 'bridge',
    icon: '🦊',
    title: '여우의 숲 다리',
    desc: '첫 번째 열 칸 다리를 완성하여 여우 친구 만나기',
    rarity: 'common',
    rarityName: '새싹',
    rarityColor: '#85a765',
  },
  {
    id: 'island-bear-bridge',
    game: 'island',
    category: 'bridge',
    icon: '🐻',
    title: '곰의 동굴 다리',
    desc: '두 번째 열 칸 다리를 짓고 곰 친구 만나기',
    rarity: 'rare',
    rarityName: '희귀',
    rarityColor: '#38bdf8',
  },
  {
    id: 'island-rabbit-bridge',
    game: 'island',
    category: 'bridge',
    icon: '🐰',
    title: '토끼의 언덕 다리',
    desc: '세 번째 다리를 완공하여 토끼 친구 만나기',
    rarity: 'rare',
    rarityName: '희귀',
    rarityColor: '#38bdf8',
  },
  {
    id: 'island-rainbow-bridge',
    game: 'island',
    category: 'bridge',
    icon: '🌈',
    title: '모든 섬의 무지개 다리',
    desc: '모든 섬을 연결하여 친구들과 축제 열기',
    rarity: 'legendary',
    rarityName: '전설',
    rarityColor: '#facc15',
  },
  {
    id: 'island-milestone-1',
    game: 'island',
    category: 'milestone',
    icon: '🌱',
    title: '첫 발걸음 배지',
    desc: '처음으로 10 만들기 퍼즐을 해결하기',
    rarity: 'common',
    rarityName: '새싹',
    rarityColor: '#85a765',
  },
  {
    id: 'island-milestone-5',
    game: 'island',
    category: 'milestone',
    icon: '🍀',
    title: '여우의 행운 클로버',
    desc: '서로 다른 5가지 열 칸 퍼즐 완성하기',
    rarity: 'rare',
    rarityName: '희귀',
    rarityColor: '#38bdf8',
  },
  {
    id: 'island-milestone-10',
    game: 'island',
    category: 'milestone',
    icon: '🍯',
    title: '곰의 황금 꿀단지',
    desc: '서로 다른 10가지 열 칸 퍼즐 완성하기',
    rarity: 'epic',
    rarityName: '영웅',
    rarityColor: '#c084fc',
  },
  {
    id: 'island-milestone-20',
    game: 'island',
    category: 'milestone',
    icon: '🥕',
    title: '토끼의 무지개 당근',
    desc: '서로 다른 20가지 열 칸 퍼즐 완성하기',
    rarity: 'epic',
    rarityName: '영웅',
    rarityColor: '#c084fc',
  },
  {
    id: 'island-milestone-45',
    game: 'island',
    category: 'milestone',
    icon: '👑',
    title: '블록섬 전설의 마스터',
    desc: '45가지 모든 10 만들기 퍼즐을 정복하기',
    rarity: 'legendary',
    rarityName: '전설',
    rarityColor: '#facc15',
  },
];
